### ISSUE TITLE
Question about Escha

### ISSUE THREAD

**Issue by aja311** [KenshiDRK/ApRadar#11]
More of a question, I cannot get mine to show the map of escha-zi'tah for me. Is there a way I can fix this?

**Comment by KenshiDRK** [comment]
it does show for me, check in the maps folder if you have a file called 120_0.gif.

**Comment by aja311** [comment]
Ok thanks! I will check that in a few minutes. I do see an escha zi’tah map called something else. Can I just use that same one and copy/rename it.

**Comment by KenshiDRK** [comment]
if its a 512x512 gif image yea, can't guarantee other image formats to work.

**Comment by aja311** [comment]
I downloaded your whole thing but it doesn’t seem to have the actual exe in it when I unzip it. So I just took the whole maps folder and put it in my working apradar3. But for some reason it doesn’t work.

**Comment by aja311** [comment]
Just the escha zi’tah map I mean.

**Comment by KenshiDRK** [comment]
thats probably cause is a old version, to get the compiler exe go here (it includes maps) https://github.com/KenshiDRK/ApRadar/releases/tag/v3.3.0.34

**Comment by aja311** [comment]
Awesome. Thanks a ton! I figured it was probably something I was doing. :p
