### ISSUE TITLE
Private Servers Pt. 2

### ISSUE THREAD

**Issue by MatthewJHBerry** [KenshiDRK/ApRadar#14]
Hello, I've tried using ProcHelp with ApRadar and Mappy and it doesn't work for either. I see others have had the issue and apparently they figured it out without really leaving any info behind for others.

atomos says he doesn't use these apps and doesn't know if his helper will even work with them. For me, it is starting the apps. No errors. It's just not allowing me to select a process.

**Comment by KenshiDRK** [comment]
I have never used it myself cause I play on retail so I can't help much here, which is the private server and how the loader is named?

**Comment by MatthewJHBerry** [comment]
Hey, thanks for the speedy response! I did actually get it figured out. You have to edit the .ini file to what your bootloader is named. I missed that part in atomos's instructions. It's good. Mappy, on the other hand, is weird.  I'm not sure what's up with it, but it looks like a something involving trying to process a x64 and not the 32-bit version of a DLL or something.

Getting:
"Unable to load the native components of SQL Server Compact corresponding to the ADO.NET provider of version 8482. Install the correct version of SQL Server Compact. Refer to KB article 974247 for more details."

But, hey. ApRadar is working. Thanks for your dedication, my friend.

**Comment by KenshiDRK** [comment]
Thats weird cause mappy has nothing to do with sql but apradar does
