### ISSUE TITLE
AP radar nonfunctional on new private server.

### ISSUE THREAD

**Issue by KaioKenMasterr** [KenshiDRK/ApRadar#19]
Had experience using all of your versions of AP radar on multiple private servers, does not seem to be functional on one of the newer servers. 

Apradar has no issue finding Pol.exe and identifying your character, but it does not have any clue where it is at or any data regarding mobs or target.

Mappy works with no issues.

Possibly a quick fix if you are able to take a peak at it.

**Comment by KenshiDRK** [comment]
what version of mappy are you using?

**Comment by KenshiDRK** [comment]
whats the private server?

**Comment by KenshiDRK** [comment]
looks like this server uses its own client so don't expect a fix, probably mappy is not 100% working as well.
