### ISSUE TITLE
No Application (.exe)

### ISSUE THREAD

**Issue by StealKeel** [KenshiDRK/ApRadar#22]
downloaded the current version and there is no way to launch

**Comment by KenshiDRK** [comment]
What you did download? the release or the source code? you get the release here https://github.com/KenshiDRK/ApRadar/releases/tag/v3.3.0.36

**Comment by KenshiDRK** [comment]
Thats the source code, you have to download the release, which is the
compiled code, you have the link above.

**Comment by StealKeel** [comment]
Thank you
