### ISSUE TITLE
ApRadar Bar

### ISSUE THREAD

**Issue by pcdavid52a** [KenshiDRK/ApRadar#5]
I recall there being a way to disable the bar from loading in some previous version of ApRadar.

Is this something that can be easily implemented?

From my limited recollection, it was something along the lines of creating a shortcut out of the executable and adding -nobar to the end of the target.

Thank you for your hard work!

**Comment by KenshiDRK** [comment]
You need to add /nobar to the shortcut you use to launch apradar, so if should look like this "yourpath\ApRadar3.exe /nobar".
If SE break it and I have to fix I'll include that in the next version.
