### ISSUE TITLE
Issues in Escha Ru'Aun

### ISSUE THREAD

**Issue by Tathamet667** [KenshiDRK/ApRadar#6]
Hi there - 2 issues to report:

1.  "View TODs" does not work; no enemies will load
2.  Selecting "Spawn Alert Filter" from the top menu bar results in ApRadar locking up.  Perhaps related to issue #1?

Thanks for the support!

**Comment by KenshiDRK** [comment]
Does it work for other zones?

**Comment by Tathamet667** [comment]
Yes, I had no problems using it during Magian Trials.

**Comment by KenshiDRK** [comment]
Im unable to make view TODs to work in south gustaberg, but I don't use apradar so maybe Im doing something wrong.

**Comment by KenshiDRK** [comment]
I fixed some errors on the dat mapping, scaning dats to add mobs should work now, atleast it works for me can you try replacing this dll and see if it works for you? (You gotta scan dats for new mob to add them)
[FFXIMemory.zip](https://github.com/KenshiDRK/ApRadar/files/5028776/FFXIMemory.zip)

**Comment by Tathamet667** [comment]
That did the trick for issue #2 - thanks!  TODs remained a blank list, but I can live without.

**Comment by KenshiDRK** [comment]
no idea whats wrong with tod list

**Comment by KenshiDRK** [comment]
looks like you need to have camping mode activated to be able to see the TODs

**Comment by Tathamet667** [comment]
Good to know, but I happen to have camping mode activated; still no TOD, in Escha Ru'Aun at least.

**Comment by KenshiDRK** [comment]
yea not working in escha, but I don't know why.

**Comment by KenshiDRK** [comment]
I think I have fixed TOD's not working on new zones, could you test it? (this doesn't include the maps)
[Apradar3.zip](https://github.com/KenshiDRK/ApRadar/files/5030307/Apradar3.zip)

**Comment by KenshiDRK** [comment]
I released a new version with more fixes, download the map pack too and erase the old map pack, I chaged the app to use primary zone id now.
