### ISSUE TITLE
Private server

### ISSUE THREAD

**Issue by DennisKerman** [KenshiDRK/ApRadar#8]
Hi, i love this app!
Now private server eden is using edenxi.exe (custom ashita) instead pol.exe and "ffxi cannot be found" as a process.
Renaming is not an option because the  i cant load the game.

I know you do this freely and i thank you so much for the hard work!

If there is no time or possibility to adress this i understand.
Best regards

**Comment by DennisKerman** [comment]
Ok sry i just looked thru closed issues.. saw the hint about prochelp32. I will try that! Sry sry

**Comment by MatthewJHBerry** [comment]
I went and downloaded it but prochelp is not working for me? Any advice Dennis?
